CREATE TABLE replies (
    id CHAR(36) PRIMARY KEY,
    content_markdown MEDIUMTEXT NOT NULL,
    content_html MEDIUMTEXT NOT NULL,
    author_id CHAR(36) NOT NULL,
    post_id CHAR(36) NOT NULL,
    parent_reply_id CHAR(36) NULL,
    depth TINYINT NOT NULL DEFAULT 0,
    like_count INT NOT NULL DEFAULT 0,
    audit_status ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'approved',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP NULL,
    last_edited_at TIMESTAMP NULL,
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_replies_post (post_id, created_at ASC),
    INDEX idx_replies_author (author_id),
    INDEX idx_replies_parent (parent_reply_id),
    INDEX idx_replies_audit (audit_status),
    CONSTRAINT fk_replies_author FOREIGN KEY (author_id) REFERENCES users(id),
    CONSTRAINT fk_replies_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_replies_parent FOREIGN KEY (parent_reply_id) REFERENCES replies(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
