CREATE TABLE posts (
    id CHAR(36) PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    content_markdown MEDIUMTEXT NOT NULL,
    content_html MEDIUMTEXT NOT NULL,
    author_id CHAR(36) NOT NULL,
    board_id CHAR(36) NOT NULL,
    cover_image_url VARCHAR(500) NULL,
    like_count INT NOT NULL DEFAULT 0,
    reply_count INT NOT NULL DEFAULT 0,
    collect_count INT NOT NULL DEFAULT 0,
    share_count INT NOT NULL DEFAULT 0,
    is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
    pin_type ENUM('none', 'board', 'global') NOT NULL DEFAULT 'none',
    is_essence BOOLEAN NOT NULL DEFAULT FALSE,
    audit_status ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'approved',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP NULL,
    deleted_by CHAR(36) NULL,
    last_edited_at TIMESTAMP NULL,
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_posts_author (author_id),
    INDEX idx_posts_board (board_id),
    INDEX idx_posts_board_created (board_id, created_at DESC),
    INDEX idx_posts_pinned (is_pinned, pin_type, created_at DESC),
    INDEX idx_posts_audit (audit_status),
    INDEX idx_posts_is_deleted (is_deleted),
    INDEX idx_posts_created_at (created_at DESC),
    FULLTEXT INDEX idx_posts_title_content (title, content_markdown),
    CONSTRAINT fk_posts_author FOREIGN KEY (author_id) REFERENCES users(id),
    CONSTRAINT fk_posts_board FOREIGN KEY (board_id) REFERENCES boards(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
